// ─────────────────────────────────────────────────────────────
// DRUM Career Conversation — Taxonomy
// Source of truth for all types in the new architecture.
// DO NOT add profiles, archetypes, or hybrid categories here.
// ─────────────────────────────────────────────────────────────

// ── Phases ──────────────────────────────────────────────────
// Represents how someone currently relates to identity,
// career construction and decision-making.
// Inferred AFTER the conversation — never detected live.

export const PHASES = [
  "Exploração",
  "Direção",
  "Autoria",
  "Consolidação",
  "Reposicionamento",
  "Legado",
] as const;

export type Phase = (typeof PHASES)[number];

// ── Pathways ─────────────────────────────────────────────────
// The ONLY valid career pathways. Source: Tipos de Carreira - Drum.pdf
// No other category exists. No hybrids. No fallback types.

export const PATHWAYS = [
  "Empreendedor",
  "Executivo",
  "Profissional liberal",
  "Consultor",
  "Acadêmico",
  "Creator / Autor",
  "Sucessor",
] as const;

export type Pathway = (typeof PATHWAYS)[number];

// ── Clarity labels ───────────────────────────────────────────
// Derived from total_points_0_to_10:
// 0–2 → Difusa | 3–4 → Emergente | 5–6 → Em construção
// 7–8 → Clara  | 9–10 → Muito clara

export const CLARITY_LABELS = [
  "Difusa",
  "Emergente",
  "Em construção",
  "Clara",
  "Muito clara",
] as const;

export type ClarityLabel = (typeof CLARITY_LABELS)[number];

export function clarityLabelFromScore(points: number): ClarityLabel {
  if (points <= 2) return "Difusa";
  if (points <= 4) return "Emergente";
  if (points <= 6) return "Em construção";
  if (points <= 8) return "Clara";
  return "Muito clara";
}

export function clarityScoreFromPoints(points: number): 1 | 2 | 3 | 4 | 5 {
  if (points <= 2) return 1;
  if (points <= 4) return 2;
  if (points <= 6) return 3;
  if (points <= 8) return 4;
  return 5;
}

// ── Tensions ─────────────────────────────────────────────────
// Temporary movement frictions — NOT identities or archetypes.
// Dynamic and contextual.

export const TENSIONS = [
  "Excesso de possibilidades",
  "Dependência de validação",
  "Construção sem autoria",
  "Impostor",
  "Movimento sem direção",
  "Falta de consistência",
  "Autonomia vs lealdade familiar",
  "Comparação constante",
] as const;

export type Tension = (typeof TENSIONS)[number];

// ── Action types ─────────────────────────────────────────────
// Fixed. Every diagnostico must have exactly one of each.

export const ACTION_TYPES = ["para_dentro", "para_fora", "prototipar"] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE_LABELS: Record<ActionType, string> = {
  para_dentro: "Para dentro",
  para_fora:   "Para fora",
  prototipar:  "Prototipar",
};

// ── Editorial content ─────────────────────────────────────────
// Fixed, curated definitions per phase and pathway.
// These appear verbatim in the result view — not generated by AI.
// The AI layer adds personal_connection / personal_fit on top.

export type PhaseEditorial = {
  definition: string;         // What this phase is — 2 sentences
  common_conflicts: string;   // What usually gets hard here — 2 sentences
};

export const PHASE_EDITORIAL: Record<Phase, PhaseEditorial> = {
  "Exploração": {
    definition:
      "Você está no momento em que o campo ainda é aberto — muitas referências, muitas perguntas, poucos compromissos firmes. A identidade profissional está sendo testada mais do que construída.",
    common_conflicts:
      "O maior risco aqui é confundir movimento com progresso: fazer muitas coisas sem que nenhuma aprofunde. A pressão externa para 'decidir logo' costuma acelerar escolhas antes do tempo.",
  },
  "Direção": {
    definition:
      "Você já tem uma aposta — um caminho que parece mais verdadeiro do que os outros. O trabalho agora é converter essa convicção em construção real, passo a passo.",
    common_conflicts:
      "A tensão típica é entre a clareza interna e a validação externa: a direção faz sentido pra você, mas ainda é difícil explicar ou provar para os outros. O medo de estar errado ainda aparece.",
  },
  "Autoria": {
    definition:
      "Você está construindo algo que é reconhecidamente seu — um projeto, uma área de domínio, uma forma de trabalhar que carrega sua identidade. A carreira deixou de ser um percurso e virou uma obra.",
    common_conflicts:
      "O desafio aqui é sustentar a autoria sob pressão: manter o fio do que você quer construir quando surgem oportunidades atraentes que puxam para fora do seu eixo.",
  },
  "Consolidação": {
    definition:
      "Você chegou a um ponto de maturidade e reconhecimento — o que você construiu tem peso, reputação e resultados. O desafio agora é menos sobre provar e mais sobre aprofundar.",
    common_conflicts:
      "A fricção comum é o tédio disfarçado de estabilidade: tudo funciona, mas algo importante sumiu. A pergunta que aparece é 'e agora — o que ainda importa construir?'",
  },
  "Reposicionamento": {
    definition:
      "Você está no meio de uma transição deliberada — saindo de um lugar que não faz mais sentido e buscando um novo eixo. Não é crise: é revisão.",
    common_conflicts:
      "O maior custo do reposicionamento é o período de ambiguidade: você já não se identifica com o que era, mas ainda não chegou no que quer ser. Isso exige tolerância ao vazio.",
  },
  "Legado": {
    definition:
      "Você está no momento em que a pergunta não é mais 'o que eu vou fazer?' mas 'o que eu quero deixar?'. A construção agora é sobre impacto, continuidade e transferência.",
    common_conflicts:
      "A tensão típica é entre o desejo de passar o bastão e a dificuldade de abrir mão do controle. Confiar que o que foi construído sobrevive sem você é o trabalho mais difícil desta fase.",
  },
};

export type PathwayEditorial = {
  definition: string;         // What this pathway is — 2 sentences
  in_practice: string;        // What it looks like concretely — 2 sentences
};

export const PATHWAY_EDITORIAL: Record<Pathway, PathwayEditorial> = {
  "Empreendedor": {
    definition:
      "O empreendedor constrói a partir da autonomia — cria estruturas novas, assume risco próprio e encontra mais sentido na fundação do que na execução dentro de algo existente.",
    in_practice:
      "Na prática, isso aparece como dificuldade de se encaixar em hierarquias rígidas, energia para identificar problemas e montar soluções, e uma necessidade real de ver o impacto direto do que faz.",
  },
  "Executivo": {
    definition:
      "O executivo encontra sentido em liderar dentro de organizações — construir times, operar em escala, e fazer sistemas complexos funcionarem melhor.",
    in_practice:
      "Na prática, isso se manifesta como atração por responsabilidade crescente, habilidade para mobilizar pessoas e uma satisfação real quando a operação performa — não apenas quando a ideia é boa.",
  },
  "Profissional liberal": {
    definition:
      "O profissional liberal constrói a partir de uma competência específica e exerce essa competência com autonomia — sem depender de uma organização para ter autoridade ou remuneração.",
    in_practice:
      "Na prática, isso aparece como desejo de ser referência num domínio claro, valorização da independência profissional, e uma relação direta entre a qualidade do trabalho e o que recebe em troca.",
  },
  "Consultor": {
    definition:
      "O consultor entrega valor através do diagnóstico e da recomendação — transita entre problemas diferentes, clientes diferentes, e encontra sentido na inteligência aplicada a contextos variados.",
    in_practice:
      "Na prática, isso se manifesta como facilidade de entrar em organizações novas e gerar valor rápido, preferência por projetos com começo e fim, e pouca afinidade com a operação de longo prazo.",
  },
  "Acadêmico": {
    definition:
      "O acadêmico constrói a partir da produção e transmissão de conhecimento — a pesquisa, o ensino e a contribuição para um campo são o eixo central de sentido profissional.",
    in_practice:
      "Na prática, isso aparece como atração pelo rigor, pelo aprofundamento progressivo e pela ideia de que o trabalho tem valor mesmo sem resultado imediato — porque contribui para algo maior.",
  },
  "Creator / Autor": {
    definition:
      "O creator ou autor constrói a partir da expressão — produz conteúdo, narrativas ou obras que refletem um ponto de vista próprio e constroem audiência ou influência ao longo do tempo.",
    in_practice:
      "Na prática, isso se manifesta como vontade de publicar, criar e compartilhar perspectivas com o mundo — e uma relação direta entre a autenticidade do que produz e o impacto que gera.",
  },
  "Sucessor": {
    definition:
      "O sucessor está posicionado para dar continuidade a algo que foi construído por outros — geralmente uma empresa ou legado familiar — e o trabalho é integrar essa herança com sua própria identidade.",
    in_practice:
      "Na prática, isso aparece como uma tensão constante entre o que foi construído antes e o que você quer construir agora, entre honrar o legado e fazer escolhas que sejam genuinamente suas.",
  },
};

// ── Structured output types ───────────────────────────────────

export type PhaseResult = {
  name: Phase;
  short_description: string;
  personal_connection: string; // AI-generated: how THIS person's story maps to the phase
  confidence: number;          // 0–1
  evidence: string[];
};

export type PathwayResult = {
  name: Pathway;
  short_description: string;
  personal_fit: string;        // AI-generated: why THIS pathway fits this person specifically
  confidence: number;          // 0–1
  evidence: string[];
};

export type ClaritycriterionResult = {
  score_0_to_2: 0 | 1 | 2;
  evidence: string;
};

export type ClarityResult = {
  score_1_to_5: 1 | 2 | 3 | 4 | 5;
  label: ClarityLabel;
  total_points_0_to_10: number;
  criteria: {
    direction_naming:    ClaritycriterionResult;
    speech_coherence:    ClaritycriterionResult;
    own_criteria:        ClaritycriterionResult;
    concrete_movement:   ClaritycriterionResult;
    ambiguity_tolerance: ClaritycriterionResult;
  };
};

export type TensionResult = {
  name: Tension;
  short_description: string;
  personal_detail: string;     // AI-generated: specific manifestation in this person's situation
  confidence: number;          // 0–1
  evidence: string[];
};

export type Action = {
  type: ActionType;
  title: string;
  description: string;
  why_this_action: string;
  timeframe: string;
};

export type DiagnosticoMetadata = {
  anxiety_score_1_to_5: number | null;
  conversation_duration_seconds: number | null;
  mentioned_people: string[];
  mentioned_projects: string[];
  raw_summary: string;
};

// ── Main diagnostico type ─────────────────────────────────────
// This is the canonical output of the inference engine.
// Matches the assessment_results table schema exactly.

export type Diagnostico = {
  phase:    PhaseResult;
  pathway:  PathwayResult;
  clarity:  ClarityResult;
  tension:  TensionResult;
  actions:  [Action, Action, Action];   // exactly 3 — one per ActionType
  metadata: DiagnosticoMetadata;
};

// ── Fallback diagnostico ──────────────────────────────────────
// Used when the Anthropic call fails.
// Intentionally generic — marked as "fallback" in ai_model.
// Actions do NOT reference conversation specifics (there are none).

export const FALLBACK_DIAGNOSTICO: Diagnostico = {
  phase: {
    name: "Exploração",
    short_description:
      "Você parece estar num momento de abertura — muitas possibilidades à vista, ainda sem uma aposta clara.",
    personal_connection:
      "Não foi possível gerar uma leitura personalizada desta vez. A leitura acima é baseada nos padrões gerais da fase.",
    confidence: 0.5,
    evidence: [],
  },
  pathway: {
    name: "Empreendedor",
    short_description:
      "Um caminho de construção própria parece presente na sua fala, mas ainda precisa de mais conversa para confirmar.",
    personal_fit:
      "Não foi possível gerar uma leitura personalizada desta vez. A leitura acima é baseada nos padrões gerais da trajetória.",
    confidence: 0.4,
    evidence: [],
  },
  clarity: {
    score_1_to_5: 2,
    label: "Emergente",
    total_points_0_to_10: 4,
    criteria: {
      direction_naming:    { score_0_to_2: 1, evidence: "Sinal insuficiente na conversa." },
      speech_coherence:    { score_0_to_2: 1, evidence: "Sinal insuficiente na conversa." },
      own_criteria:        { score_0_to_2: 1, evidence: "Sinal insuficiente na conversa." },
      concrete_movement:   { score_0_to_2: 0, evidence: "Sinal insuficiente na conversa." },
      ambiguity_tolerance: { score_0_to_2: 1, evidence: "Sinal insuficiente na conversa." },
    },
  },
  tension: {
    name: "Excesso de possibilidades",
    short_description:
      "A principal fricção parece ser a quantidade de caminhos abertos — cada escolha parece exigir fechar os outros.",
    personal_detail:
      "Não foi possível gerar uma leitura personalizada desta vez. A leitura acima é baseada nos padrões gerais desta tensão.",
    confidence: 0.4,
    evidence: [],
  },
  actions: [
    {
      type: "para_dentro",
      title: "Escreva o que você não quer",
      description:
        "Pegue 15 minutos e escreva uma lista do que você definitivamente não quer construir nos próximos 3 anos. Sem justificar — só listar.",
      why_this_action:
        "Fechar portas é mais fácil do que abrir. A lista do que não quer revela o que sobra.",
      timeframe: "7 dias",
    },
    {
      type: "para_fora",
      title: "Converse com alguém que escolheu",
      description:
        "Mande mensagem para uma pessoa que você admira e que tomou uma decisão de carreira nos últimos 5 anos. Pergunte como foi o momento de decidir.",
      why_this_action:
        "Ver como outra pessoa navegou a escolha concreta é mais útil do que continuar analisando as opções sozinho.",
      timeframe: "7 dias",
    },
    {
      type: "prototipar",
      title: "Teste uma direção por uma semana",
      description:
        "Escolha um dos caminhos que aparecem na sua cabeça. Dedique 30 minutos por dia, durante 7 dias, a algo concreto relacionado a ele — sem compromisso definitivo.",
      why_this_action:
        "Uma semana de experiência real vale mais do que semanas de análise. O objetivo não é decidir: é gerar dados.",
      timeframe: "7 dias",
    },
  ],
  metadata: {
    anxiety_score_1_to_5: null,
    conversation_duration_seconds: null,
    mentioned_people: [],
    mentioned_projects: [],
    raw_summary: "Diagnóstico gerado com fallback — conversa não pôde ser processada.",
  },
};
